# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/planolux',
                'doc_host': 'https://iohazard.github.io',
                'git_url': 'https://github.com/iohazard/planolux',
                'lib_path': 'planolux'},
  'syms': {'planolux.core': {'planolux.core.foo': ('core.html#foo', 'planolux/core.py')}}}
